# FCFS or LS
ALGORITHM: FCFS
# PREEMPTIVE of NON-PREEMPTIVE
OPERATION_MODE: PREEMPTIVE
# 5 <= PROCESS_NUM <= 25
PROCESS_NUM: 5
# ARRIVAL TIME
ARRIVAL_TIME: 50
# WORK LOAD
WORK_LOAD: 20
# BILLS
BILLS: 10
# QUANTUM
QUANTUM: 1000
