# FCFS or LOTTERY
ALGORITHM: FCFS
PARAMETERS:
# True of False
PREEMPTIVE: True
# 5 <= PROCESS_NUM <= 25
PROCESS_NUM: 5
# ARRIVAL TIME
ARRIVAL_TIME: 50
# WORK LOAD
WORK_LOAD: 20
# FCFS PARAMETERS
FCFS_PARAMETERS:

LOTTERY_PARAMETERS:
  TICKETS_NUM:
QUANTUM: 10
